-- Background push notifications: reminders arrive even when Jarvis is closed.
--
-- How it works (all on the free plan):
--   1. Each device that allows notifications registers a Web Push subscription.
--   2. Every reminder stores notify_at — the exact moment (UTC) it should alert.
--   3. pg_cron calls the `push-reminders` Edge Function once a minute.
--   4. The function atomically claims due reminders and sends encrypted Web Push
--      messages (VAPID) to that person's devices via Apple / Google / Mozilla.

create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

-- ---------------------------------------------------------------------------
-- Reminders: when to alert, and which alert time has already been pushed
-- ---------------------------------------------------------------------------
alter table public.reminders
  add column notify_at  timestamptz,
  add column pushed_for timestamptz;

create index reminders_due_push_idx on public.reminders (notify_at)
  where done = false and notify_at is not null;

-- ---------------------------------------------------------------------------
-- Push subscriptions (one per device/browser)
-- ---------------------------------------------------------------------------
create table public.push_subscriptions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  endpoint     text not null unique check (endpoint ~ '^https://' and char_length(endpoint) <= 1000),
  p256dh       text not null check (char_length(p256dh) <= 200),
  auth         text not null check (char_length(auth) <= 100),
  device       text not null default '' check (char_length(device) <= 120),
  created_at   timestamptz not null default now(),
  last_used_at timestamptz
);
create index push_subscriptions_user_idx on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;
create policy "Own devices: read"   on public.push_subscriptions for select to authenticated using ((select auth.uid()) = user_id);
create policy "Own devices: delete" on public.push_subscriptions for delete to authenticated using ((select auth.uid()) = user_id);
revoke all on public.push_subscriptions from anon;
-- Inserts go through register_push() below so a browser that changes hands
-- (sign-out → someone else signs in) is moved to the new owner cleanly.
revoke insert, update on public.push_subscriptions from authenticated;

create or replace function public.register_push(p_endpoint text, p_p256dh text, p_auth text, p_device text default '')
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Not signed in'; end if;
  -- The endpoint is an unguessable URL that only this browser holds; whoever
  -- registers it now owns it, so a previous owner stops receiving pushes here.
  delete from public.push_subscriptions where endpoint = p_endpoint and user_id <> uid;
  insert into public.push_subscriptions (user_id, endpoint, p256dh, auth, device)
  values (uid, p_endpoint, p_p256dh, p_auth, left(coalesce(p_device, ''), 120))
  on conflict (endpoint) do update
    set p256dh = excluded.p256dh, auth = excluded.auth, device = excluded.device;
end;
$$;
revoke execute on function public.register_push(text, text, text, text) from public, anon;
grant execute on function public.register_push(text, text, text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Private server config (never exposed through the API)
-- ---------------------------------------------------------------------------
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table private.push_config (
  id          integer primary key default 1 check (id = 1),
  vapid       jsonb,         -- signing keys, generated by the Edge Function on first use
  public_key  text,          -- application server key handed to browsers
  cron_secret text not null default encode(extensions.gen_random_bytes(32), 'hex')
);
insert into private.push_config (id) values (1);

-- Server-only helpers for the Edge Function (service_role).
create or replace function public.push_config_get()
returns table (vapid jsonb, public_key text, cron_secret text)
language sql
security definer
set search_path = ''
as $$ select vapid, public_key, cron_secret from private.push_config where id = 1 $$;

create or replace function public.push_config_set_vapid(p_vapid jsonb, p_public_key text)
returns table (vapid jsonb, public_key text)
language sql
security definer
set search_path = ''
as $$
  update private.push_config set vapid = p_vapid, public_key = p_public_key
   where id = 1 and push_config.vapid is null;
  select vapid, public_key from private.push_config where id = 1;
$$;

-- Atomically claim reminders whose alert time has arrived (so each alert is sent once).
create or replace function public.claim_due_pushes()
returns table (id uuid, user_id uuid, title text, notes text, date date, "time" text, notify_at timestamptz)
language sql
security definer
set search_path = ''
as $$
  update public.reminders r
     set pushed_for = r.notify_at
   where r.done = false
     and r.notify_at is not null
     and r.notify_at <= now()
     and r.notify_at > now() - interval '12 hours'
     and r.pushed_for is distinct from r.notify_at
  returning r.id, r.user_id, r.title, r.notes, r.date, r.time, r.notify_at
$$;

revoke execute on function public.push_config_get() from public, anon, authenticated;
revoke execute on function public.push_config_set_vapid(jsonb, text) from public, anon, authenticated;
revoke execute on function public.claim_due_pushes() from public, anon, authenticated;
grant execute on function public.push_config_get() to service_role;
grant execute on function public.push_config_set_vapid(jsonb, text) to service_role;
grant execute on function public.claim_due_pushes() to service_role;

-- ---------------------------------------------------------------------------
-- Every minute: ask the Edge Function to send anything that's due.
-- The shared secret is read from the private table at run time.
-- ---------------------------------------------------------------------------
select cron.schedule(
  'jarvis-push-reminders',
  '* * * * *',
  $$
  select net.http_post(
    url := 'https://vruuhfekedmriypljdbo.supabase.co/functions/v1/push-reminders',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', (select cron_secret from private.push_config where id = 1)
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 25000
  );
  $$
);
